name: Schedule Visit Website
 
on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"  # 每天1点运行一次
  push:
    branches:
      - main 
jobs:
  visit-website:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Visit Website
        run: |
          curl https://webhost.zlzgz.eu.org/a089c89c-d794-4153-a116-9aeeeb4fd669
